### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by stephenmathieson** [duojs/css-compat#4]
```
$ git rev-parse --short HEAD
d611f18
$ node -v
v0.11.14
$ make test
child_process: customFds option is deprecated, use stdio instead.


  duo
    1) should load css deps
    2) should ignore duo-compatible syntax
    3) should handle the in between state of logo/rocket-fuel@0.2.0
    4) should support loading only styles
    5) should work with hybrids
    ✓ should CSS deps that dont have a styles or main (656ms)


  1 passing (4s)
  5 failing

  1) duo should load css deps:
     AssertionError: false == true
      at Context.<anonymous> (/Users/stephenmathieson/repos/github.com/duojs/css-compat/test/index.js:27:5)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/stephenmathieson/repos/github.com/duojs/css-compat/node_modules/co-mocha/node_modules/co/index.js:59:19)

  2) duo should ignore duo-compatible syntax:
     AssertionError: false == true
      at Context.<anonymous> (/Users/stephenmathieson/repos/github.com/duojs/css-compat/test/index.js:32:5)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/stephenmathieson/repos/github.com/duojs/css-compat/node_modules/co-mocha/node_modules/co/index.js:59:19)

  3) duo should handle the in between state of logo/rocket-fuel@0.2.0:
     AssertionError: false == true
      at Context.<anonymous> (/Users/stephenmathieson/repos/github.com/duojs/css-compat/test/index.js:37:5)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/stephenmathieson/repos/github.com/duojs/css-compat/node_modules/co-mocha/node_modules/co/index.js:59:19)

  4) duo should support loading only styles:
     AssertionError: false == true
      at Context.<anonymous> (/Users/stephenmathieson/repos/github.com/duojs/css-compat/test/index.js:42:5)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/stephenmathieson/repos/github.com/duojs/css-compat/node_modules/co-mocha/node_modules/co/index.js:59:19)

  5) duo should work with hybrids:
     AssertionError: false == true
      at Context.<anonymous> (/Users/stephenmathieson/repos/github.com/duojs/css-compat/test/index.js:47:5)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/Users/stephenmathieson/repos/github.com/duojs/css-compat/node_modules/co-mocha/node_modules/co/index.js:59:19)



make: *** [test] Error 5
```

**Comment by stephenmathieson** [comment]
tests seem to pass now?

**Comment by dominicbarnes** [comment]
Haha, oh yeah I think there was some slight whitespace discrepancy or something that caused them to fail. (or one of the upstream deps it was using changed ever-so-slightly)
